name: esip-tech-dive
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - nomkl
  - boto3
  - dask
  - dask-kubernetes
  - dask-labextension
  - datashader
  - distributed
  - gcsfs
  - geopandas
  - geoviews-core
  - python-graphviz
  - hvplot
  - intake
  - intake-xarray
  - ipyleaflet
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - msgpack-python
  - nbserverproxy
  - rasterio
  - requests
  - s3fs
  - sat-search
  - xarray
  - zarr
